/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jfugue.guitar;

import java.awt.Dimension;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.netbeans.api.settings.ConvertAsProperties;
import org.musician.api.CentralLookup;
//import org.netbeans.modules.musician.gui.score.ScoreTopComponent;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.InstanceContent;
import org.openide.util.lookup.ServiceProvider;
import org.openide.windows.Mode;
import org.openide.windows.WindowManager;

@TopComponent.Description(preferredID = "GuitarTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = true, position = 20)
@ActionID(category = "Window", id = "org.jfugue.guitar.GuitarTopComponent")
@ActionReference(path = "Menu/Window" /*
 * , position = 333
 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_GuitarAction",
preferredID = "GuitarTopComponent")
public final class GuitarTopComponent extends TopComponent {

//    Mode editorMode = WindowManager.getDefault().findMode("editor");
//    private ScoreTopComponent scoreTopComponent;
    private final GuitarJTable table;
    
    private InstanceContent ic = new InstanceContent();

    public GuitarTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(GuitarTopComponent.class, "CTL_GuitarTopComponent"));
        setToolTipText(NbBundle.getMessage(GuitarTopComponent.class, "HINT_GuitarTopComponent"));
        table = new GuitarJTable(this, ic);
        add(table);
        table.setPreferredSize(new Dimension(1014, 174));
        associateLookup(new AbstractLookup(ic));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
