package org.jfugue.newcomposition;

import javax.swing.ImageIcon;
import javax.swing.JPanel;
import org.openide.util.ImageUtilities;

public final class CompositionVisualPanel1 extends JPanel {
    
    /** Creates new form CompositionVisualPanel1 */
    public CompositionVisualPanel1() {
        initComponents();
        cbxClefItemStateChanged(null);
    }
    
    public String getName() {
        return "Composition parameters";
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        edtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxKeySignature = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxRythmCount = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cbxRythmUnit = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        edtTempo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edtVolume = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbxClef = new javax.swing.JComboBox();
        imgClef1 = new javax.swing.JLabel();
        imgClef2 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Title :");

        edtTitle.setText("Untitled");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Key-signature :");

        cbxKeySignature.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "C maj", "G maj (1 sharp)", "D maj (2 sharps)", "A maj (3 sharps)", "E maj (4 sharps)", "B maj (5 sharps)", "Fis maj (6 sharps)", "Cis maj (7 sharps)", "F maj (1 flat)", "Bb maj (2 flats)", "Eb maj (3 flats)", "Ab maj (4 flats)", "Db maj (5 flats)", "Gb maj (6 flats)", "Cb maj (7 flats)" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Rythm");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "unit :");

        cbxRythmCount.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "8", "9", "12" }));
        cbxRythmCount.setSelectedIndex(3);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, "count :");

        cbxRythmUnit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "4", "8", "16", "32" }));
        cbxRythmUnit.setSelectedIndex(2);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, "Tempo :");

        edtTempo.setText("60");
        edtTempo.setToolTipText("");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel7, "Volume :");

        edtVolume.setText("100");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel8, "(%)");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel9, "(numerator)");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel10, "(denominator)");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel11, "(quarters / minute)");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel12, "Clef :");

        cbxClef.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "G-clef", "F-clef", "C-clef", "Treble-clef", "Alto-clef", "Tenor-clef", "Bass-clef" }));
        cbxClef.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxClefItemStateChanged(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(imgClef1, "    ");
        imgClef1.setMaximumSize(new java.awt.Dimension(18, 30));
        imgClef1.setMinimumSize(new java.awt.Dimension(18, 30));
        imgClef1.setPreferredSize(new java.awt.Dimension(18, 30));

        org.openide.awt.Mnemonics.setLocalizedText(imgClef2, "    ");
        imgClef2.setMaximumSize(new java.awt.Dimension(18, 30));
        imgClef2.setMinimumSize(new java.awt.Dimension(18, 30));
        imgClef2.setPreferredSize(new java.awt.Dimension(18, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel12)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxRythmUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxRythmCount, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxClef, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(imgClef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(imgClef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cbxKeySignature, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbxRythmCount, cbxRythmUnit, edtTempo, edtVolume});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxClef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(imgClef1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imgClef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxKeySignature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxRythmCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxRythmUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edtVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void cbxClefItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxClefItemStateChanged
        char c = getClef();
        imgClef2.setIcon(null);
        switch( c ) {
            case 'G':
                imgClef1.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/G-clef-icon.png", true)));
                break;
            case 'F':
                imgClef1.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/F-clef-icon.png", true)));
                break;
            case 'C':
                imgClef1.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/C-clef-icon.png", true)));
                break;
            case 'T':
                imgClef1.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/C-clef-icon.png", true)));
                break;
            case 'P':
                imgClef1.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/G-clef-icon.png", true)));
                imgClef2.setIcon(new ImageIcon(ImageUtilities.loadImage("org/netbeans/modules/musician/resources/F-clef-icon.png", true)));
                break;
        }
    }//GEN-LAST:event_cbxClefItemStateChanged
    
    public String getTitle() {
        return edtTitle.getText();
    }
    
    public char getClef() {
        String s = (String) cbxClef.getSelectedItem();
        switch (s) {
            case "G-clef":
            case "Treble-clef":
                return 'G';
            case "F-clef":
            case "Bass-clef":
                return 'F';
            case "C-clef":
            case "Alto-clef":
                return 'C';
            case "T-clef":
            case "Tenor-clef":
                return 'T';
            case "Piano staves":
                return 'P';
        }
        
        return ' ';       
    }
    
    public String getKeySignature() {
        return (String) cbxKeySignature.getSelectedItem();
    }
    
    public int getRythmCount() {
        return new Integer((String)cbxRythmCount.getSelectedItem());
    }
    
    public int getRythmUnit() {
        return new Integer((String)cbxRythmUnit.getSelectedItem());
    }
    
    public int getTempo() {
        return new Integer(edtTempo.getText());
    }
    
    public int getVolume() {
        return new Integer(edtVolume.getText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxClef;
    private javax.swing.JComboBox cbxKeySignature;
    private javax.swing.JComboBox cbxRythmCount;
    private javax.swing.JComboBox cbxRythmUnit;
    private javax.swing.JTextField edtTempo;
    private javax.swing.JTextField edtTitle;
    private javax.swing.JTextField edtVolume;
    private javax.swing.JLabel imgClef1;
    private javax.swing.JLabel imgClef2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
    
}

