/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.jfugue.xylophone;

import java.awt.BorderLayout;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.openide.util.lookup.AbstractLookup;
import org.openide.util.lookup.AbstractLookup.Content;
import org.openide.util.lookup.InstanceContent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.jfugue.xylophone//Xylophone//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "XylophoneTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(position = 30, mode = "output", openAtStartup = true)
@ActionID(category = "Window", id = "org.jfugue.xylophone.XylophoneTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_XylophoneAction",
preferredID = "XylophoneTopComponent")
@Messages({
    "CTL_XylophoneAction=Xylophone",
    "CTL_XylophoneTopComponent=Xylophone",
    "HINT_XylophoneTopComponent=This is a Xylophone window"
})
public final class XylophoneTopComponent extends TopComponent {

    private final InstanceContent ic = new InstanceContent();

    public XylophoneTopComponent() {
        initComponents();
        setName(Bundle.CTL_XylophoneTopComponent());
        setToolTipText(Bundle.HINT_XylophoneTopComponent());
        setLayout(new BorderLayout());
        add(new Xylophone(ic), BorderLayout.CENTER);
        associateLookup(new AbstractLookup(ic));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
