on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [6, 7, 8, 8.0.144, 11, 15, 16, 17-ea]
    steps:
    - uses: foojayio/setup-java@disco
    - run: java -version
    - uses: foojayio/setup-java@disco
      with:
        distribution: 'zulu'
        java-version: ${{matrix.java}}  
    - run: java -version
   
