on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8.092, 11.0.1, 11.0.12, 17.0.1]
    steps:
    - uses: actions/checkout@v2
    - run: java -version
    - uses: foojayio/setup-java@disco
      with:
        distro: 'liberica'
        java-version: ${{matrix.java}}  
    - run: java -version
   
